#!/usr/bin/env python3
"""Regenerate derived artifacts from the canonical 40-data/ sources.

Outputs (never hand-edit these):
  1. 40-data/zoning_standards.csv          — flat projection of zones/*.json
  2. markdown zone notes' standards region  — between the BEGIN/END:standards markers
     (+ mirrored numeric frontmatter fields)
  3. 30-reference/parking-ratios-by-use.md  — between the BEGIN/END:parking markers

Usage:
  python sync.py            apply changes
  python sync.py --check    exit 1 if anything would change (drift detection; writes nothing)

stdlib only.
"""
import csv
import json
import re
import sys
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parents[1]
VAULT_DIR = DATA_DIR.parent
ZONES_DIR = DATA_DIR / "zones"
CHECK = "--check" in sys.argv

STD_BEGIN = "<!-- BEGIN:standards (generated by 40-data/_tools/sync.py — do not edit) -->"
STD_END = "<!-- END:standards -->"
PARK_BEGIN = "<!-- BEGIN:parking (generated by 40-data/_tools/sync.py — do not edit) -->"
PARK_END = "<!-- END:parking -->"
ZONES_BEGIN = "<!-- BEGIN:zones-table (generated by 40-data/_tools/sync.py — do not edit) -->"
ZONES_END = "<!-- END:zones-table -->"

CSV_COLUMNS = ["zone_id", "jurisdiction_id", "jurisdiction_name", "zone_code", "zone_name",
               "category", "min_lot_size_sf", "min_lot_width_ft", "max_density_dua", "max_far",
               "max_lot_coverage_pct", "max_height_ft", "max_stories", "front_setback_ft",
               "side_setback_ft", "rear_setback_ft", "parking_ratio", "source_doc",
               "source_citation", "source_page", "provenance", "confidence", "human_verified", "notes"]

# (table label, standards key, units, frontmatter key)
STD_ROWS = [
    ("Max density", "max_density_dua", "du/acre", "max_density_dua"),
    ("Max FAR", "max_far", "ratio", "max_far"),
    ("Min lot size", "min_lot_size_sf", "sf", "min_lot_size_sf"),
    ("Min lot width", "min_lot_width_ft", "ft", None),
    ("Max lot coverage", "max_lot_coverage_pct", "%", None),
    ("Max building height", "max_height_ft", "ft", "max_height_ft"),
    ("Max stories", "max_stories", "stories", None),
    ("Front setback", "front_setback_ft", "ft", ("setbacks", "front")),
    ("Side setback", "side_setback_ft", "ft", ("setbacks", "side")),
    ("Rear setback", "rear_setback_ft", "ft", ("setbacks", "rear")),
    ("Parking", "parking_ratio", "spaces/unit or /1,000 sf", "parking_ratio"),
]

changed_files = []


def num_str(v):
    if isinstance(v, float) and v.is_integer():
        return str(int(v))
    return str(v)


def csv_cell(v):
    if v is None:
        return ""
    if v == "TBD":
        return "TBD"
    if isinstance(v, (int, float)):
        return num_str(v)
    return str(v)


def load_sources():
    out = {}
    p = DATA_DIR / "source_registry.csv"
    if p.exists():
        with p.open(newline="", encoding="utf-8") as f:
            for row in csv.DictReader(f):
                out[row["source_id"]] = row
    return out


def load_zone_files():
    files = []
    if ZONES_DIR.exists():
        for jf in sorted(ZONES_DIR.glob("*.json")):
            files.append(json.loads(jf.read_text(encoding="utf-8")))
    return files


def replace_marked(text, label, new_block):
    """Replace a single <!-- BEGIN:{label} ... END:{label} --> region (tolerant of
    both the bare and the '(generated ...)' marker forms). Returns (text, replaced?).
    If duplicate marker pairs exist, collapses them to a single block."""
    pat = re.compile(r"<!--\s*BEGIN:" + re.escape(label) + r"\b.*?<!--\s*END:" + re.escape(label) + r"\s*-->", re.DOTALL)
    matches = pat.findall(text)
    if not matches:
        return text, False
    # Replace the first occurrence with new_block; drop any further duplicates.
    first = [True]

    def _sub(m):
        if first[0]:
            first[0] = False
            return new_block
        return ""
    return pat.sub(_sub, text), True


def write_if_changed(path, text):
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == text:
        return False
    changed_files.append(str(path.relative_to(VAULT_DIR)))
    if not CHECK:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
    return True


# ---------- 1. zoning_standards.csv ----------

def build_csv(zone_files):
    rows = []
    for data in zone_files:
        jid = data.get("jurisdiction_id", "")
        jname = data.get("jurisdiction_name", "")
        default_src = data.get("default_source_doc", "")
        for z in data.get("zones", []):
            std = z.get("standards") or {}
            rows.append({
                "zone_id": z.get("zone_id", ""),
                "jurisdiction_id": jid,
                "jurisdiction_name": jname,
                "zone_code": z.get("zone_code", ""),
                "zone_name": z.get("zone_name", ""),
                "category": z.get("category", ""),
                "min_lot_size_sf": csv_cell(std.get("min_lot_size_sf")),
                "min_lot_width_ft": csv_cell(std.get("min_lot_width_ft")),
                "max_density_dua": csv_cell(std.get("max_density_dua")),
                "max_far": csv_cell(std.get("max_far")),
                "max_lot_coverage_pct": csv_cell(std.get("max_lot_coverage_pct")),
                "max_height_ft": csv_cell(std.get("max_height_ft")),
                "max_stories": csv_cell(std.get("max_stories")),
                "front_setback_ft": csv_cell(std.get("front_setback_ft")),
                "side_setback_ft": csv_cell(std.get("side_setback_ft")),
                "rear_setback_ft": csv_cell(std.get("rear_setback_ft")),
                "parking_ratio": csv_cell(std.get("parking_ratio")),
                "source_doc": z.get("source_doc") or default_src,
                "source_citation": z.get("source_citation", ""),
                "source_page": csv_cell(z.get("source_page")),
                "provenance": z.get("provenance", ""),
                "confidence": z.get("confidence", ""),
                "human_verified": z.get("human_verified", ""),
                "notes": z.get("notes", ""),
            })
    rows.sort(key=lambda r: r["zone_id"])
    import io
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=CSV_COLUMNS, lineterminator="\n")
    w.writeheader()
    w.writerows(rows)
    return buf.getvalue()


# ---------- 2. markdown zone notes ----------

def requirement_cell(v, citation):
    if v is None or v == "TBD" or v == "":
        tail = f"verify against {citation}" if citation else "verify against source"
        return f"TBD — {tail}"
    if isinstance(v, (int, float)):
        return num_str(v)
    return str(v)


def standards_block(zone, sources):
    std = zone.get("standards") or {}
    citation = zone.get("source_citation", "")
    src_id = zone.get("source_doc", "")
    src_title = sources.get(src_id, {}).get("title", src_id)
    prov = zone.get("provenance", "unknown")
    conf = zone.get("confidence", "tbd")
    page = zone.get("source_page")
    hv = zone.get("human_verified", "")

    lines = [STD_BEGIN, ""]
    lines.append("## Development Standards")
    lines.append("")
    prov_label = {"official-pdf": "official document (PDF)", "official-html": "official code (HTML)",
                  "secondary-mirror": "secondary mirror", "inferred": "inferred", "unknown": "unknown"}.get(prov, prov)
    conf_label = f"human-verified {hv}" if hv else f"{conf}, unverified"
    lines.append(f"*Generated from `40-data/zones/{zone['zone_id'].split(':')[0]}.json` — "
                 f"provenance: {prov_label}; confidence: {conf_label}. Do not edit between the markers.*")
    lines.append("")
    lines.append("| Standard | Requirement | Units | Code Citation | Notes |")
    lines.append("|----------|-------------|-------|---------------|-------|")
    for label, key, units, _ in STD_ROWS:
        req = requirement_cell(std.get(key), citation)
        cite = citation if (std.get(key) not in (None, "", "TBD")) else ""
        lines.append(f"| {label} | {req} | {units} | {cite} | |")
    lines.append("")
    pg = f", p.{page}" if page else ""
    verif = f"verified {hv}" if hv else f"{conf} — UNVERIFIED (human verification pending)"
    lines.append(f"Source: {src_title} {citation}{pg} — {verif}.")
    lines.append("")
    lines.append(STD_END)
    return "\n".join(lines)


def update_frontmatter(fm, zone):
    """Mirror confirmed numeric values into frontmatter lines. fm is a list of lines."""
    std = zone.get("standards") or {}

    def fmt(v):
        if v is None or v == "TBD" or v == "":
            return '"TBD"'
        if isinstance(v, (int, float)):
            return num_str(v)
        return '"' + str(v).replace('"', "'") + '"'

    def set_scalar(key, value):
        pat = re.compile(rf"^(\s*{re.escape(key)}\s*:)(.*)$")
        for i, line in enumerate(fm):
            if pat.match(line):
                # preserve any trailing comment
                comment = ""
                m = re.search(r"(\s+#.*)$", line)
                if m:
                    comment = m.group(1)
                fm[i] = pat.match(line).group(1) + " " + fmt(value) + comment
                return

    def set_setback(sub, value):
        for i, line in enumerate(fm):
            if re.match(r"^\s*setbacks\s*:", line):
                for j in range(i + 1, len(fm)):
                    if re.match(rf"^\s+{sub}\s*:", fm[j]):
                        indent = re.match(r"^(\s*)", fm[j]).group(1)
                        fm[j] = f"{indent}{sub}: {fmt(value)}"
                        return
                    if not re.match(r"^\s+\w", fm[j]):
                        return
                return

    for _, key, _, fmkey in STD_ROWS:
        if fmkey is None:
            continue
        val = std.get(key)
        if isinstance(fmkey, tuple):
            set_setback(fmkey[1], val)
        else:
            set_scalar(fmkey, val)
    return fm


def update_zone_note(zone, sources):
    note_rel = zone.get("note_path")
    if not note_rel:
        return
    path = VAULT_DIR / note_rel
    if not path.exists():
        print(f"  skip (note not found): {note_rel}")
        return
    text = path.read_text(encoding="utf-8")

    # split frontmatter
    fm_match = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if fm_match:
        fm_lines = fm_match.group(1).split("\n")
        # Safety guard: never overwrite a human-curated note's standards/frontmatter.
        status = next((l.split(":", 1)[1].strip().strip('"').strip("'")
                       for l in fm_lines if l.strip().startswith("status:")), "")
        if status in ("reviewed", "authoritative"):
            print(f"  skip (status: {status}, human-curated — not overwriting): {note_rel}")
            return
        fm_lines = update_frontmatter(fm_lines, zone)
        new_fm = "---\n" + "\n".join(fm_lines) + "\n---\n"
        body = text[fm_match.end():]
    else:
        new_fm = ""
        body = text

    block = standards_block(zone, sources)

    body, replaced = replace_marked(body, "standards", block)
    if not replaced:
        # replace the existing "## Development Standards" section (heading .. next "## ")
        lines = body.split("\n")
        start = next((i for i, l in enumerate(lines) if l.strip().lower() == "## development standards"), None)
        if start is not None:
            end = next((i for i in range(start + 1, len(lines)) if lines[i].startswith("## ")), len(lines))
            lines[start:end] = [block, ""]
            body = "\n".join(lines)
        else:
            # no section: insert after first H1, else prepend
            h1 = next((i for i, l in enumerate(body.split("\n")) if l.startswith("# ")), None)
            blines = body.split("\n")
            insert_at = (h1 + 1) if h1 is not None else 0
            blines[insert_at:insert_at] = ["", block, ""]
            body = "\n".join(blines)

    write_if_changed(path, new_fm + body)


# ---------- 2b. jurisdiction overview standards table ----------

def load_overview_paths():
    out = {}
    p = DATA_DIR / "jurisdictions.csv"
    if p.exists():
        with p.open(newline="", encoding="utf-8") as f:
            for row in csv.DictReader(f):
                out[row["jurisdiction_id"]] = row.get("vault_path", "").strip()
    return out


def dim(v):
    return "—" if v in (None, "", "TBD") else (num_str(v) if isinstance(v, (int, float)) else str(v))


def zones_table(data):
    lines = [ZONES_BEGIN, ""]
    lines.append("## Zone Standards (data-linked)")
    lines.append("")
    lines.append(f"*Generated from `40-data/zones/{data['jurisdiction_id']}.json` via `sync.py`. "
                 f"`—` = not yet extracted. Full data: `40-data/zoning_standards.csv`. Do not edit between the markers.*")
    lines.append("")
    lines.append("| Zone | Name | Category | Min Lot (sf) | Density (du/ac) | FAR | Height (ft) | Front | Side | Rear | Parking | Conf. |")
    lines.append("|------|------|----------|--------------|-----------------|-----|-------------|-------|------|------|---------|-------|")
    for z in sorted(data.get("zones", []), key=lambda z: z.get("zone_code", "")):
        s = z.get("standards") or {}
        conf = "✔ verified" if z.get("human_verified") else z.get("confidence", "")
        lines.append("| {code} | {name} | {cat} | {lot} | {den} | {far} | {ht} | {fr} | {sd} | {rr} | {pk} | {cf} |".format(
            code=z.get("zone_code", ""), name=z.get("zone_name", ""), cat=z.get("category", ""),
            lot=dim(s.get("min_lot_size_sf")), den=dim(s.get("max_density_dua")), far=dim(s.get("max_far")),
            ht=dim(s.get("max_height_ft")), fr=dim(s.get("front_setback_ft")), sd=dim(s.get("side_setback_ft")),
            rr=dim(s.get("rear_setback_ft")), pk=dim(s.get("parking_ratio")), cf=conf))
    lines.append("")
    lines.append(ZONES_END)
    return "\n".join(lines)


def update_overview_table(data, overview_paths):
    rel = overview_paths.get(data.get("jurisdiction_id", ""), "")
    if not rel:
        return
    path = VAULT_DIR / rel
    if not path.exists():
        print(f"  skip (overview not found): {rel}")
        return
    text = path.read_text(encoding="utf-8")
    block = zones_table(data)
    text, replaced = replace_marked(text, "zones-table", block)
    if not replaced:
        text = text.rstrip() + "\n\n" + block + "\n"
    write_if_changed(path, text)


# ---------- 3. parking reference note ----------

def build_parking_section():
    rows = []
    p = DATA_DIR / "parking_standards.csv"
    if p.exists():
        with p.open(newline="", encoding="utf-8") as f:
            rows = [r for r in csv.DictReader(f)]
    lines = [PARK_BEGIN, ""]
    lines.append("*Generated from `40-data/parking_standards.csv`. Do not edit between the markers.*")
    lines.append("")
    if not rows:
        lines.append("_No verified parking ratios recorded yet. Populate `40-data/parking_standards.csv` as zones are extracted._")
    else:
        lines.append("| Jurisdiction | Use | Ratio | Basis | Citation | Confidence |")
        lines.append("|--------------|-----|-------|-------|----------|------------|")
        for r in sorted(rows, key=lambda r: (r["jurisdiction_id"], r["use_type"])):
            conf = f"verified {r['human_verified']}" if r.get("human_verified") else f"{r['confidence']}"
            lines.append(f"| {r['jurisdiction_id']} | {r['use_type']} | {r['ratio']} | "
                         f"{r['unit_basis']} | {r['source_citation']} | {conf} |")
    lines.append("")
    lines.append(PARK_END)
    return "\n".join(lines)


def update_parking_note():
    path = VAULT_DIR / "30-reference" / "parking-ratios-by-use.md"
    if not path.exists():
        print("  skip (parking ref note not found)")
        return
    text = path.read_text(encoding="utf-8")
    section = build_parking_section()
    text, replaced = replace_marked(text, "parking", section)
    if not replaced:
        text = text.rstrip() + "\n\n" + section + "\n"
    write_if_changed(path, text)


def main():
    sources = load_sources()
    zone_files = load_zone_files()
    overview_paths = load_overview_paths()

    write_if_changed(DATA_DIR / "zoning_standards.csv", build_csv(zone_files))
    for data in zone_files:
        for z in data.get("zones", []):
            update_zone_note(z, sources)
        update_overview_table(data, overview_paths)
    update_parking_note()

    if CHECK:
        if changed_files:
            print("sync.py --check: DRIFT — these would change:")
            for f in changed_files:
                print(f"  {f}")
            return 1
        print("sync.py --check: clean (no drift)")
        return 0
    if changed_files:
        print(f"sync.py: updated {len(changed_files)} file(s):")
        for f in changed_files:
            print(f"  {f}")
    else:
        print("sync.py: nothing to update")
    return 0


if __name__ == "__main__":
    sys.exit(main())
